# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 408d951e1b243c15d3c8a4124f70051a266604e3a37823d59d9f947f569a633e55d7c846d8cc4c89b5f4e8993f780f4307eebc6598e46f966e43a309746acaf6

test:
  secret_key_base: 0bde07aef6c706212a7592cb0741f40ab544db08a0ae49ca3acfe7087c3726ca27a6b67ce94cbe66f4a3bcf962fb122347615aafb2ce3b82ff5be69ef398d5de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
